name: Docs

on:
  push:
    paths:
      - 'docs/**'
      - 'scripts/generate_llms_txt.py'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install MkDocs
        run: pip install mkdocs mkdocs-material
      - name: Generate llms.txt
        run: python scripts/generate_llms_txt.py
      - name: Build site
        run: mkdocs build --strict
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site
